<h3>Add voucher status</h3>

<?php $record = $block->getRecord(); ?>

<form action="<?= $block->getFormAction(); ?>" method="post">
    <input name="status_code" type="text" value="<?php isset($record) && print $record->getStatusCode(); ?>" />
    <input name="id" type="hidden" value="<?php isset($record) && print $record->getId(); ?>" />
    <br /><br />
    <input type="submit" value="Send" class="action primary" />
</form>

<br />

<a href="<?= $block->getUrl('customervouchers/voucher_status/index'); ?>" class="action primary">Back</a>
